"""add_youtube_support

Revision ID: 1033de0fb71e
Revises: 75b885f0bf29
Create Date: 2025-10-02 23:11:25.967874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1033de0fb71e'
down_revision: Union[str, Sequence[str], None] = '75b885f0bf29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('youtube_url', sa.String(), nullable=True))
    op.alter_column('videos', 'is_live_stream',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('videos', 'is_live_stream',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_column('videos', 'youtube_url')
    # ### end Alembic commands ###
