"""add channel features and subscriptions

Revision ID: 25ba87989c0d
Revises: 2e146880bff4
Create Date: 2025-10-02 12:36:26.914457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25ba87989c0d'
down_revision: Union[str, Sequence[str], None] = '2e146880bff4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('subscriber_id', sa.Integer(), nullable=False),
    sa.Column('subscribed_to_id', sa.Integer(), nullable=False),
    sa.Column('subscribed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['subscribed_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['subscriber_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('subscriber_id', 'subscribed_to_id')
    )
    op.add_column('users', sa.Column('channel_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('channel_description', sa.String(), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('banner_url', sa.String(), nullable=True))
    op.add_column('videos', sa.Column('views', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'views')
    op.drop_column('users', 'banner_url')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'channel_description')
    op.drop_column('users', 'channel_name')
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
