"""add processing status to videos

Revision ID: 2e146880bff4
Revises: 2fa747ea8d3f
Create Date: 2025-10-02 12:20:57.292070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e146880bff4'
down_revision: Union[str, Sequence[str], None] = '2fa747ea8d3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('processing_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'processing_status')
    # ### end Alembic commands ###
