"""Add duration and hls_path to videos

Revision ID: 2fa747ea8d3f
Revises: ac28f2169c3c
Create Date: 2025-10-02 11:14:53.831439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fa747ea8d3f'
down_revision: Union[str, Sequence[str], None] = 'ac28f2169c3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('hls_path', sa.String(), nullable=True))
    op.add_column('videos', sa.Column('duration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'duration')
    op.drop_column('videos', 'hls_path')
    # ### end Alembic commands ###
