"""add_likes_dislikes_system

Revision ID: c9e68a49eaa7
Revises: 25ba87989c0d
Create Date: 2025-10-02 12:51:51.690903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9e68a49eaa7'
down_revision: Union[str, Sequence[str], None] = '25ba87989c0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('is_like', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_likes_id'), 'video_likes', ['id'], unique=False)
    op.add_column('videos', sa.Column('likes', sa.Integer(), nullable=True))
    op.add_column('videos', sa.Column('dislikes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'dislikes')
    op.drop_column('videos', 'likes')
    op.drop_index(op.f('ix_video_likes_id'), table_name='video_likes')
    op.drop_table('video_likes')
    # ### end Alembic commands ###
